language: python
python:
- 2.7
install: true
script:
- deactivate
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-16.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-16.04-amd64.tar.gz
- sudo apt install python-minimal
- source dx-toolkit/environment
# Install secure version of urllib3 library
- sudo pip install urllib3[secure]
- python --version
- python build_workflow.py --run-tests
env:
  global:
    secure: flEkVopPnQyThxTgkRSJvKKlkOdSdTaNHfhmzyNQBvg/mMg5dCJzE3I5ZT1fpGCblXUY3KOWyqu5jfrDRpABF6JSgwZNdv17bmXqGCgoO/OCyBie2+AhQxkdOREoksLHcSGK0WJ/0hov0/a6z9ed4O07dEDJanc9wRmnooeewUd3PVw5G/3QaXPcJUadf3pIcxLJp9hiQHRSeFGEBG89cImZh9vcVwVcWqXNF3B+CqB3O0YCZdLzCjIhGGgEm5H3b91fAMYqTN8zp4QWXKh3dIkHQMKCvBWpJdUnhAR8Zyysob0e+aZcEIrgOon8klhpW62DpA/jzg9XAaxmew9eP7IpCY1PY9nm3Lqqc9ons6Zn6lxV64f/yvQieeANrSTS0lxUk276mNxSsdUVP+u5m0dtM0KMLoD2oju1HTftE42Sj5atIH4IyxGUGi2rG2PuW06lWHTN9a5HDtRXQUuXlhonhybq1suYdfXD7rEn/tiifnyKqhXJ8DnMdAZXwL7pn0zGPHlOce8AARcWh8UOOynLUB9PFBSUC0X9r1ai4VdJEJxE5krstmYAK1IxyzEuu9rmaWUM5OWzFbEhytZKapxYq2YsDpXItfN8fJy7Tx7U54HWsqKaV5ZeNj4ZZIz77E0HQm30x7pgm1Zi/AqwtWdiXG0FtowlfGi/xKK2Wio=
