language: python
python:
- 2.7
install: true
script:
- deactivate
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- python build_workflow.py --run-tests
env:
  global:
    secure: Gle383QXDtGE3WC7Vy/nqaq5qL6o1IEN0JKxhtRYCo8B5hAKNuRBRYu3Cely8uDy/UoHWeyP+8lxFiBFqNqKe00nLInUgkgeL0sEKRzk3ck6p8CUfoK0D2+DNnvQg2Ai3iNFcrr3/uOG0jNuM6qNF/Dn6eqhq3lYEuE8Ct71LPtjqE7RgT6LChEv0d8DGxfR3A45T4l1JxWtr+Ty+rajfyP0dPFnakNaZEtEpXaeXCJ2EEN5jz+SBkdSss4KBMhL+D2NNU19+Lo/EuGgGaws86hOR9HN5L4fpXRgkKbiywwmmKntHeqfr1x0QREq/UOLAYSvt2jf8EXiPraqPBSbuSIXRQwg0XkmY2tI5m+UCNYSlo+orhHxQdKIEqrtNCd/l9+TnDa6uw+m4jx2jhYAD91ICPrIBOBoJ8aix6PdNefm4scg4TK3m1P6o2UHSGQeHu71o+XWINmrlf+gBVXyJWU0YCHNp6vp93HHvTwbPSsb5VA7x2Z5eBmN/o+3Xb6UVLOwFnENKmqQDVIprGSxuSkJs5A3F0wmq/OjPLGihnAXMhPy9qgRzStGWRluvfg3LyNGrxhQK27ic921/TeSLX0AhnptbCagLR00Mpk8Od+Raip5aqLvtASGvxryv/3dPf0KqV51jJRhLVQuReYuS3QywAb3rnLjzhDYxT1lepg=
