language: python
python:
- 2.7
install: true
script:
- deactivate
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-16.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-16.04-amd64.tar.gz
- source dx-toolkit/environment
- pip install --user urllib3[secure]
- python --version
- python build_workflow.py --run-tests
env:
  global:
    secure: 
dd:
  secure: XTf08IRhte3fDtf1MXIo+Z9QYpY6uGaTe4Y49OMS/OianZUZSF3QeC6ik6gSUgIh+5cs052+IH5hL+ukq7lySy06zrX5vz3c0AFmWFT+T23u7U7mpfEg5iO65CroL4695XQoEwSpNv7kChgTLtK4spgmc5lNIDO9XfVVDZQ0LIifNkKMxWp1Ojfwdb/XlZHJtZQwGFYT8//hM8FJY6PdnolcuowxHchgdKWc3tz2KQ+4mxQmbRlSW65XWFNAH0beaqgXt89FcH9iO0thrbDmqZstn47PCaaAd5C67vWB3eeFny3sDSrkcW4N1fyHWgLRzPS9/YuPbRIe/7EJlodCavgGw9JjSAAzGKpVvpeXA1R7Y5cF6mK8ySQyE6UrxXeaQ2iSbIWGfPJBP7D8X1fzdBty9pO4FZKM9kKZKp+R1ruCs7cE68NIY3mp4oRvGvg5Lr/ZkFuYXl+btpFTDUrDcQ+7ZndkekYHSkVA3HPtU9CCIFN3bxj8sZS5L4WEzdxco+veG1ji7SjJesJwQ4xwQ73sqyhA9/0DkwSoCYsGAtA3qUCME8ASLJ8R6c4BzB40ZMSqEkpyk/uwwE1TmX1Te2TqGXqQaHHU+4H77KbS28MLETi6sn5cGQR/hMSAApdkYAw1n+ho1n5KTtKfgxTy3XiI/30rWjx2HOc8zR3DTfA=
