language: python
python:
- 2.7.9
install: true
script:
- deactivate
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- python build_workflow.py --run-tests
env:
  global:
    secure: yHwW1lss5xlUd6RsuMfPtqLxNidGxej5dk8gVBgwe0uSoO64Citok8Qco6BoHbWSHe6G99+eXeDbFL/CcPopFbLiTXykTSzJPg0FYn5E+VNqDpVUuKZQnagRgkMXNSeGNb0s7vKQ+hlVGrEg69KUVRv3+LgL1lr0YvSjUZeNFL5qxYiaBp+z/ZnMjTZ7tBuaFT0mX0zzJpGt/cpmo2of2x2ZK7a9gYFDfx7PAiKKGAWM1kzYpabirvO7JodDFhINWf+Sta6GQQL58RiX7FzF8cyzJm4bOA2cpXTYKS4bHjxJEJwYa3IdKuAnWh6s7E1oJc8gWqgebJ2zNkThXaZm/eLMO+CsN5lg7QUuJtbJApNr3B7LgVFnaOwkAOqjAHtrJjyO9bMDetzvAEjuBGeNKUX5JLx6AJjcbFmVjZnFLkwwQ8rYlHzZvhLwQWsEHX259d95xlO7lqpHx2no76/pxLCS8FnKRPkhnz6ocx96hKYo5nN31deOsGT25WD7+vGts8Wjq9cgIQPqE6D6hAn22NtVnMFtOZUSdxqdzkJ2x6azvRW6zHDqeXkA/pqMzW1RaYRl55vEysY9KlZNMWGqffBq7h5sHAcS2bg+zRUiHa6cU2/TJ6yrsi5LW2HzWRjiarIiTo/tIyrrp/NOPYeUvuIdE+3wJxRObgpy5yEN4WI=
